<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260216204657 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE solve (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, room_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1E65F3B4A76ED395 ON solve (user_id)');
        $this->addSql('CREATE INDEX IDX_1E65F3B454177093 ON solve (room_id)');
        $this->addSql('ALTER TABLE solve ADD CONSTRAINT FK_1E65F3B4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE solve ADD CONSTRAINT FK_1E65F3B454177093 FOREIGN KEY (room_id) REFERENCES room (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE solve DROP CONSTRAINT FK_1E65F3B4A76ED395');
        $this->addSql('ALTER TABLE solve DROP CONSTRAINT FK_1E65F3B454177093');
        $this->addSql('DROP TABLE solve');
    }
}
